# Generated by Django 5.2.5 on 2025-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує підтвердження'), ('CONFIRMED', 'Підтверджене'), ('PROCESSING', 'Обробляється'), ('SHIPPED', 'Відправлено'), ('DELIVERED', 'Доставлено'), ('CANCELED', 'Скасоване'), ('RETURNED', 'Повернення')], default='PENDING', max_length=15)),
                ('total_price', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('CASH_ON_DELIVERY', 'Готівка при отриманні'), ('CARD_ONLINE', 'Банківська карта онлайн'), ('CARD_ON_DELIVERY', 'Карта при отриманні')], default='CASH_ON_DELIVERY', max_length=30)),
                ('shipping_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
