# Generated by Django 5.2.5 on 2025-09-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='created_at',
        ),
    ]
